export const DASHBOARD_DATA = {
  shell: {
    logoText: 'Progresio',
    logoutButton: 'Logout',
  },
  boardList: {
    title: 'Your Boards',
    newBoardButton: 'New Board',
    emptyTitle: 'No boards yet',
    emptyDescription: 'Create your first board to get started.',
    columnsLabel: 'columns',
    membersLabel: 'members',
    deleteConfirm: 'Are you sure you want to delete this board?',
  },
  createBoard: {
    title: 'Create New Board',
    nameLabel: 'Board Name',
    namePlaceholder: 'e.g. Product Roadmap',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'What is this board for?',
    cancelButton: 'Cancel',
    submitButton: 'Create Board',
    submittingButton: 'Creating...',
  },
  kanban: {
    addColumnButton: 'Add Column',
    addColumnPlaceholder: 'Column name',
    deleteColumnConfirm: 'Delete this column and all its tasks?',
    deleteBoardButton: 'Delete Board',
    backButton: 'Back to Boards',
  },
  taskCard: {
    deleteButton: 'Delete',
    deleteConfirm: 'Delete this task?',
    noDueDate: 'No due date',
  },
  createTask: {
    placeholder: 'Task title',
    addButton: 'Add',
    cancelButton: 'Cancel',
    unassigned: 'Unassigned',
    errorFallback: 'Failed to create task. Please try again.',
  },
  defaultColumns: ['To Do', 'In Progress', 'Done'],
  priorities: {
    low: { label: 'Low', color: '#22C55E' },
    medium: { label: 'Medium', color: '#EAB308' },
    high: { label: 'High', color: '#EF4444' },
    urgent: { label: 'Urgent', color: '#DC2626' },
  },
  members: {
    panelTitle: 'Members',
    addButton: 'Add Member',
    removeButton: 'Remove',
    ownerBadge: 'Owner',
    removeConfirm: 'Remove this member? Their task assignments will be cleared.',
  },
  taskDetail: {
    title: 'Task Details',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Add a description...',
    priorityLabel: 'Priority',
    assigneeLabel: 'Assignee',
    dueDateLabel: 'Due Date',
    labelsLabel: 'Labels',
    addLabelPlaceholder: 'Add label',
    saveButton: 'Save',
    savingButton: 'Saving...',
    deleteButton: 'Delete Task',
  },
  labels: {
    colors: [
      { name: 'Red', value: '#EF4444' },
      { name: 'Orange', value: '#F97316' },
      { name: 'Yellow', value: '#EAB308' },
      { name: 'Green', value: '#22C55E' },
      { name: 'Blue', value: '#3B82F6' },
      { name: 'Purple', value: '#8B5CF6' },
      { name: 'Pink', value: '#EC4899' },
      { name: 'Gray', value: '#6B7280' },
    ],
  },
}
